architect:
  - order
  - amihaiemil
  - test
env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
merge:
  commanders:
    - salikjan
  script: |-
    mvn clean install -Pcheckstyle
decrypt:
  settings.xml: "repo/rcfg/settings.xml.asc"
  pubring.gpg: "repo/rcfg/pubring.gpg.asc"
  secring.gpg: "repo/rcfg/secring.gpg.asc"
release:
  script: |-
    chmod +x ./rrv.sh
    ./rrv.sh
